# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: s390x-qemu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        arch: [s390x]  
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Check out code
      uses: actions/checkout@v4

    - name: Test SM2EC
      run: go test -v ./internal/sm2ec/...
      env:
        GOARCH: ${{ matrix.arch }}   
  
    - name: Test SM2
      run: go test -v -short ./sm2/...
      env:
        GOARCH: ${{ matrix.arch }}   
  
    - name: Test KDF
      run: go test -v -short ./kdf/...
      env:
        GOARCH: ${{ matrix.arch }}     
 
    
